* Current Setup for Production

python generateDelphesPythia.py for pure pythia8
python generateDelphesSample.py for madgraph+pythia8

For running over CMS data:
../install/Delphes-3.4.1/DelphesCMSFWLite Cards/delphes_card_CMS.tcl delphesCMS_test.root /xrootd/store/mc/RunIISummer16DR80Premix/QCD_Pt-15to7000_TuneCUETP8M1_FlatP6_13TeV_pythia8/AODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/110000/00D5AF84-33B7-E611-8E07-D067E5F91B8A.root

Running on the batch system, use runCMS.jds (uses runCMS.sh and delphesCMS.py)

* Running Madgraph+Pythia8+Delphes

source setup.sh

../install/MG5_aMC_v2_5_5/bin/mg5_aMC 
import model sm-ckm_no_b_mass
define p = u c s d b u~ c~ s~ d~ b~ g
define j = u c s d b u~ c~ s~ d~ b~ g
generate p p > j j
add process p p > j j j
output QCD_HT500toInf -nojpeg
launch
done
Cards/QCD_HT500toInf_run_card.dat
done
# generates events
quit

gunzip ./QCD_HT500toInf/Events/run_01/unweighted_events.lhe.gz

./DelphesPythia8 Cards/delphes_card_CMS.tcl Cards/configLHE_HT500.cmnd delphes_HT500.root


../install/MG5_aMC_v2_5_5/bin/mg5_aMC 
import model sm-ckm_no_b_mass
define p = u c s d b u~ c~ s~ d~ b~ g
define j = u c s d b u~ c~ s~ d~ b~ g
generate p p > j j
add process p p > j j j
output QCD_HT50to500 -nojpeg
launch
done
Cards/QCD_HT50to500_run_card.dat
done
# generates events
quit

gunzip ./QCD_HT50to500/Events/run_01/unweighted_events.lhe.gz

./DelphesPythia8 Cards/delphes_card_CMS.tcl Cards/configLHE_HT50.cmnd delphes_HT50.root


* Herwig

eg for D-Y
cp <HERWIGPATH>/share/Herwig/LHC-Matchbox.in .

read the input file

Herwig read LHC-Matchbox.in

run the event generation

Herwig run LHC-Matchbox.run

Herwig run LHC-Matchbox.run -N 1000

* Pythia/Madgraph

** Generate events

Run MadGraph to generate di- and tri-jet events

../install/MG5_aMC_v2_5_5/bin/mg5_aMC 
generate p p > j j
add process p p > j j j
output 23_jets
launch
done
done
quit

Outputs: 23_jets/Events/run_01/unweighted_events.lhe.gz

Run Delphes+Pythia8 to hadronize and generate detector
simulation. Need to modify the LHE.cmnd card to point to the output of
MadGraph.

export PYTHIA8DATA=/cms/home/iwatson/scratch/install/share/Pythia8/xmldoc
./DelphesPythia8 Cards/delphes_card_CMS.tcl Cards/configLHE.cmnd delphes_2jet.root

[2017-07-04 Tue]

For my 3-jet generation using the CMS QCD_HT file for 2TeV+ jets, the
following seems to be necessary in the pythia8 cmnd file:

JetMatching:merge = on
JetMatching:scheme = 1
JetMatching:setMad = on
JetMatching:qCut = 10.0
! JetMatching:coneRadius = 1.0
JetMatching:etaJetMax = 10.0
JetMatching:nJetMax = 3
! JetMatching:doShowerKt = 0

Not sure how much of this is good or bad but, it also vetoes lots of
events. [note, set to 'JetMatching:exclusive = 2' by default, which i
think is right, and the 'JetMatching:nJet=2' also seems to do nothing,
the only thing we really seem to be changing is the nJetMax]

Trying also to directly run pythia8 with Madgraph (The MG5+Py8+Delphes
seemed to be missing parton matching capabilities but)

** Installing

Install MG5 by downloading it.

To install DelphesPythia8, need to change the Makefile

ifeq ($(HAS_PYTHIA8),true)
ifneq ($(PYTHIA8),)
CXXFLAGS += -I$(PYTHIA8)/include
CXXFLAGS += -I$(PYTHIA8)/include/Pythia8
OPT_LIBS += -L$(PYTHIA8)/lib -lpythia8 -ldl -lz
----> LDFLAGS +=  -L$(PYTHIA8)/lib -lpythia8 -ldl -lz
endif
endif

or else the linking doesn't work properly.


