#!/usr/bin/env python2
# --*-- mode: python --*--

import os
import subprocess
import MG5
import sys

mg5 = subprocess.Popen(os.getenv("HOME")+'/install/MG5_aMC_v2_6_0/bin/mg5_aMC', stdout=subprocess.PIPE, stdin=subprocess.PIPE)

sys.stdout.flush()
print mg5.communicate(input=MG5.cmd)
sys.stdout.flush()

print "Running Pythia"
sys.stdout.flush()
os.system("gzcat ./MG5/"+MG5.name+"/Events/run_01/tag_1_pythia8_events.hepmc.gz | ~/install/delphes/DelphesHepMC Cards/delphes_card_CMS.tcl root/"+MG5.name+".root")
sys.stdout.flush()
